services:
  - type: web
    name: veterans-benefits-assistant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ASSISTANT_NAME
        sync: false
      - key: FIRECRAWL_API_KEY
        sync: false
